#[derive(Debug, PartialEq, Eq, Clone)]
pub enum TokenType {
    Class,
    Constructor,
    Function,
    Method,
    Field,
    Static,
    Var,
    Int,
    Char,
    Boolean,
    Void,
    True,
    False,
    Null,
    This,
    Let,
    Do,
    If,
    Else,
    While,
    Return,
    LBrace,
    RBrace,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Dot,
    Comma,
    Semicolon,
    Plus,
    Minus,
    Asterisk,
    Slash,
    Ampersand,
    Pipe,
    LessThan,
    GreaterThan,
    Equal,
    Tilde,
    IntegerConstant(u16),
    StringConstant(String),
    Identifier(String),
    Error{message: String},
}

impl TokenType {
    pub fn get_category(&self) -> TokenTypeCategory {
        match self {
            TokenType::Class => TokenTypeCategory::Class,
            TokenType::Constructor => TokenTypeCategory::Constructor,
            TokenType::Function => TokenTypeCategory::Function,
            TokenType::Method => TokenTypeCategory::Method,
            TokenType::Field => TokenTypeCategory::Field,
            TokenType::Static => TokenTypeCategory::Static,
            TokenType::Var => TokenTypeCategory::Var,
            TokenType::Int => TokenTypeCategory::Int,
            TokenType::Char => TokenTypeCategory::Char,
            TokenType::Boolean => TokenTypeCategory::Boolean,
            TokenType::Void => TokenTypeCategory::Void,
            TokenType::True => TokenTypeCategory::True,
            TokenType::False => TokenTypeCategory::False,
            TokenType::Null => TokenTypeCategory::Null,
            TokenType::This => TokenTypeCategory::This,
            TokenType::Let => TokenTypeCategory::Let,
            TokenType::Do => TokenTypeCategory::Do,
            TokenType::If => TokenTypeCategory::If,
            TokenType::Else => TokenTypeCategory::Else,
            TokenType::While => TokenTypeCategory::While,
            TokenType::Return => TokenTypeCategory::Return,
            TokenType::LBrace => TokenTypeCategory::LBrace,
            TokenType::RBrace => TokenTypeCategory::RBrace,
            TokenType::LParen => TokenTypeCategory::LParen,
            TokenType::RParen => TokenTypeCategory::RParen,
            TokenType::LBracket => TokenTypeCategory::LBracket,
            TokenType::RBracket => TokenTypeCategory::RBracket,
            TokenType::Dot => TokenTypeCategory::Dot,
            TokenType::Comma => TokenTypeCategory::Comma,
            TokenType::Semicolon => TokenTypeCategory::Semicolon,
            TokenType::Plus => TokenTypeCategory::Plus,
            TokenType::Minus => TokenTypeCategory::Minus,
            TokenType::Asterisk => TokenTypeCategory::Asterisk,
            TokenType::Slash => TokenTypeCategory::Slash,
            TokenType::Ampersand => TokenTypeCategory::Ampersand,
            TokenType::Pipe => TokenTypeCategory::Pipe,
            TokenType::LessThan => TokenTypeCategory::LessThan,
            TokenType::GreaterThan => TokenTypeCategory::GreaterThan,
            TokenType::Equal => TokenTypeCategory::Equal,
            TokenType::Tilde => TokenTypeCategory::Tilde,
            TokenType::IntegerConstant(_) => TokenTypeCategory::IntegerConstant,
            TokenType::StringConstant(_) => TokenTypeCategory::StringConstant,
            TokenType::Identifier(_) => TokenTypeCategory::Identifier,
            TokenType::Error { .. } => TokenTypeCategory::Error,
        }
    }
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub enum TokenTypeCategory {
    Class,
    Constructor,
    Function,
    Method,
    Field,
    Static,
    Var,
    Int,
    Char,
    Boolean,
    Void,
    True,
    False,
    Null,
    This,
    Let,
    Do,
    If,
    Else,
    While,
    Return,
    LBrace,
    RBrace,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Dot,
    Comma,
    Semicolon,
    Plus,
    Minus,
    Asterisk,
    Slash,
    Ampersand,
    Pipe,
    LessThan,
    GreaterThan,
    Equal,
    Tilde,
    IntegerConstant,
    StringConstant,
    Identifier,
    Error,
}